package com.tcl.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tcl.database.User;
import com.tcl.database.Msgs;

import com.tcl.database.UserDao;
import com.tcl.database.MsgsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig msgsDaoConfig;

    private final UserDao userDao;
    private final MsgsDao msgsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        msgsDaoConfig = daoConfigMap.get(MsgsDao.class).clone();
        msgsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        msgsDao = new MsgsDao(msgsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Msgs.class, msgsDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        msgsDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MsgsDao getMsgsDao() {
        return msgsDao;
    }

}
